services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    
  worker:
    build: .
    env_file:
      - .env
    command: celery -A bookstore_manager worker --loglevel=info
    depends_on:
      - db
      - redis

  beat:
    build: .
    env_file:
      - .env
    command: celery -A bookstore_manager beat --loglevel=info
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0       # starts vite dev server
    ports:
      - "5173:5173"  # vite dev server
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web

volumes:
  postgres_data:
