# Generated by Django 5.2.1 on 2025-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_restockevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockevent',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
