# Generated by Django 5.2.1 on 2025-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_restockevent_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockevent',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
